<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Account;

/**
 * Import COA dari Accurate Accounting ke tabel accounts M2B.
 * Kode Accurate (format: 110-00) tidak akan bentrok dengan kode M2B (format: 1101).
 * Aman dijalankan berulang — updateOrCreate by code.
 * Tidak mengubah akun yang sudah ada.
 */
class OldDataCoaSeeder extends Seeder
{
    // Mapping tipe akun Accurate -> tipe M2B
    private array $typeMap = [
        'Kas & Bank'                => 'kas_bank',
        'Piutang Usaha'             => 'piutang',
        'Aset Lancar Lainnya'       => 'aset_lancar_lain',
        'Aset Tetap'                => 'aset_tetap',
        'Akumulasi Penyusutan'      => 'aset_tetap',
        'Aset Lainnya'              => 'aset_lancar_lain',
        'Utang Usaha'               => 'hutang_lancar',
        'Liabilitas Jangka Pendek'  => 'hutang_lancar',
        'Liabilitas Jangka Panjang' => 'hutang_jangka_panjang',
        'Modal'                     => 'modal',
        'Pendapatan'                => 'pendapatan',
        'Beban Pokok Penjualan'     => 'beban_pokok',
        'Beban'                     => 'beban_operasional',
        'Beban Lainnya'             => 'beban_lain',
        'Pendapatan Lainnya'        => 'pendapatan',
    ];

    // COA dari Accurate (194 akun) — [code, name, accurate_type]
    private array $accounts = [
        ['110-00', 'Kas',                                             'Kas & Bank'],
        ['110-01', 'Kas M2B',                                         'Kas & Bank'],
        ['120-00', 'Bank',                                            'Kas & Bank'],
        ['120-01', 'Giro Mandiri - 106.0055.89.8889',                 'Kas & Bank'],
        ['120-02', 'Tabungan Mandiri - 106.0558.98.8880',             'Kas & Bank'],
        ['130-00', 'Piutang Usaha',                                   'Piutang Usaha'],
        ['130-01', 'Piutang Usaha IDR',                               'Piutang Usaha'],
        ['130-02', 'Piutang Usaha (Lainnya)',                         'Piutang Usaha'],
        ['130-03', 'Cadangan Kerugian Piutang',                       'Piutang Usaha'],
        ['130-04', 'Piutang lainnya',                                 'Piutang Usaha'],
        ['130-05', 'Uang Muka Pembelian',                             'Piutang Usaha'],
        ['131-00', 'Piutang Lain-Lain - Pihak Ketiga',               'Aset Lancar Lainnya'],
        ['131-11', 'Piutang Karyawan - Ananda Rizky',                 'Aset Lancar Lainnya'],
        ['131-12', 'Piutang Karyawan - Sunanda',                      'Aset Lancar Lainnya'],
        ['131-13', 'Piutang Karyawan - Budi',                         'Aset Lancar Lainnya'],
        ['131-14', 'Piutang Karyawan - Sahari',                       'Aset Lancar Lainnya'],
        ['131-15', 'Piutang Karyawan - Fitri Handayani',              'Aset Lancar Lainnya'],
        ['131-16', 'Piutang Karyawan - Indrawan',                     'Aset Lancar Lainnya'],
        ['131-17', 'Piutang Karyawan - Dila',                         'Aset Lancar Lainnya'],
        ['131-18', 'Piutang Karyawan - Nurul',                        'Aset Lancar Lainnya'],
        ['131-19', 'Piutang Karyawan - Abu Bakar',                    'Aset Lancar Lainnya'],
        ['131-20', 'Piutang Karyawan - Hani',                         'Aset Lancar Lainnya'],
        ['131-21', 'Piutang Karyawan - Nova',                         'Aset Lancar Lainnya'],
        ['131-30', 'Piutang PT. Fatiha Sakti',                        'Aset Lancar Lainnya'],
        ['131-31', 'Piutang PT. Cipta Piranti',                       'Aset Lancar Lainnya'],
        ['131-32', 'Piutang PT. Kirim Email Indonesia',               'Aset Lancar Lainnya'],
        ['132-00', 'Piutang Lain-lain - Pihak Berelasi',              'Aset Lancar Lainnya'],
        ['132-11', 'Piutang PT. Fraser Masindo Boiler',               'Aset Lancar Lainnya'],
        ['150-10', 'Biaya Dibayar Dimuka',                            'Aset Lancar Lainnya'],
        ['150-11', 'Biaya Dibayar Di Muka',                           'Aset Lancar Lainnya'],
        ['150-12', 'Biaya Dibayar Di Muka - Asuransi Leasing',        'Aset Lancar Lainnya'],
        ['155-10', 'Pajak Dibayar Dimuka',                            'Aset Lancar Lainnya'],
        ['155-11', 'PPN Masukan (Accurate)',                          'Aset Lancar Lainnya'],
        ['155-15', 'PPN - LB/KB',                                     'Aset Lancar Lainnya'],
        ['155-21', 'PPh 21 Dibayar Dimuka',                           'Aset Lancar Lainnya'],
        ['155-22', 'PPh 23 Dibayar Dimuka (Accurate)',                'Aset Lancar Lainnya'],
        ['155-23', 'PPh 25',                                          'Aset Lancar Lainnya'],
        ['155-24', 'PPh 29',                                          'Aset Lancar Lainnya'],
        ['155-25', 'PPh Pasal 4 (2)',                                 'Aset Lancar Lainnya'],
        ['170-00', 'Aktiva Tetap',                                    'Aset Tetap'],
        ['170-20', 'Aset Tetap - Tanah',                              'Aset Tetap'],
        ['170-21', 'Aset Tetap - Bangunan',                           'Aset Tetap'],
        ['170-22', 'Aset Tetap - Kendaraan (Accurate)',               'Aset Tetap'],
        ['170-23', 'Aset Tetap - Peralatan & Perlengkapan Kantor',    'Aset Tetap'],
        ['170-24', 'Aset Tak Berwujud',                               'Aset Tetap'],
        ['172-10', 'Akumulasi Penyusutan Aset Tetap',                 'Akumulasi Penyusutan'],
        ['172-21', 'Akumulasi Penyusutan - Bangunan',                 'Akumulasi Penyusutan'],
        ['172-22', 'Akumulasi Penyusutan - Peralatan Kantor',         'Akumulasi Penyusutan'],
        ['172-23', 'Akumulasi Penyusutan - Kendaraan',                'Akumulasi Penyusutan'],
        ['180-00', 'Asset Lainnya',                                   'Aset Lainnya'],
        ['180-49', 'Akumulasi Amortisasi',                            'Aset Lainnya'],
        ['210-10', 'Hutang Usaha',                                    'Utang Usaha'],
        ['210-11', 'Hutang Usaha IDR',                                'Utang Usaha'],
        ['210-12', 'Uang Muka Penjualan IDR',                         'Utang Usaha'],
        ['215-10', 'Hutang Lain-Lain',                                'Liabilitas Jangka Pendek'],
        ['215-11', 'Hutang Pembelian Belum Ditagih',                  'Liabilitas Jangka Pendek'],
        ['215-12', 'Hutang Lain Lain',                                'Liabilitas Jangka Pendek'],
        ['218-11', 'Hutang Lain-lain - Pihak Berelasi',               'Liabilitas Jangka Pendek'],
        ['218-12', 'Hutang - PT. Bensuli Asam Sawit',                 'Liabilitas Jangka Pendek'],
        ['218-13', 'Hutang - PT. Indomas Teknik Perkasa',             'Liabilitas Jangka Pendek'],
        ['218-14', 'Hutang - PT. Multi Ganda Medan',                  'Liabilitas Jangka Pendek'],
        ['218-15', 'Hutang - Ibu Eka Mayang Sari',                    'Liabilitas Jangka Pendek'],
        ['218-16', 'Hutang - Bp. Benny Tarigan',                      'Liabilitas Jangka Pendek'],
        ['218-17', 'Hutang - Ibu Apinta',                             'Liabilitas Jangka Pendek'],
        ['221-10', 'Biaya Yang Masih Harus Dibayar',                  'Liabilitas Jangka Pendek'],
        ['221-11', 'Hutang Gaji (Accurate)',                          'Liabilitas Jangka Pendek'],
        ['221-12', 'Hutang THR & Bonus',                              'Liabilitas Jangka Pendek'],
        ['221-15', 'Biaya Terhutang Lainnya',                         'Liabilitas Jangka Pendek'],
        ['222-10', 'Hutang Pajak',                                    'Liabilitas Jangka Pendek'],
        ['222-11', 'PPN Keluaran (Accurate)',                         'Liabilitas Jangka Pendek'],
        ['222-12', 'Hutang Pajak - PPh 21',                           'Liabilitas Jangka Pendek'],
        ['222-13', 'Hutang Pajak - PPh 23',                           'Liabilitas Jangka Pendek'],
        ['222-14', 'Hutang Pajak - PPh 25',                           'Liabilitas Jangka Pendek'],
        ['222-15', 'Hutang Pajak - PPh 29',                           'Liabilitas Jangka Pendek'],
        ['222-16', 'Hutang Pajak - PPh Psl. 4(2)',                    'Liabilitas Jangka Pendek'],
        ['222-17', 'Hutang PPN',                                      'Liabilitas Jangka Pendek'],
        ['235-10', 'Hutang Leasing',                                  'Liabilitas Jangka Panjang'],
        ['235-11', 'PT Clipan Finance (Leasing)',                     'Liabilitas Jangka Panjang'],
        ['300-00', 'Ekuitas',                                         'Modal'],
        ['310-00', 'Modal Saham',                                     'Modal'],
        ['310-11', 'Ekuitas Saldo Awal',                              'Modal'],
        ['310-12', 'Tambahan Modal Disetor',                          'Modal'],
        ['350-00', 'Laba Ditahan (Accurate)',                         'Modal'],
        ['350-10', 'Deviden',                                         'Modal'],
        ['350-11', 'Laba Ditahan',                                    'Modal'],
        ['400-00', 'Pendapatan',                                      'Pendapatan'],
        ['401-00', 'Pendapatan Usaha (Accurate)',                     'Pendapatan'],
        ['410-00', 'Pendapatan Reimbursement (Accurate)',             'Pendapatan'],
        ['459-00', 'Return/Claim Penjualan/Diskon',                   'Pendapatan'],
        ['459-11', 'Diskon Penjualan IDR',                            'Pendapatan'],
        ['459-12', 'Diskon Penjualan Barang',                         'Pendapatan'],
        ['459-13', 'Retur Pendapatan',                                'Pendapatan'],
        ['510-00', 'Biaya Langsung',                                  'Beban Pokok Penjualan'],
        ['510-12', 'Biaya Ekspor',                                    'Beban Pokok Penjualan'],
        ['510-13', 'Biaya Impor',                                     'Beban Pokok Penjualan'],
        ['510-14', 'Biaya Operasional Ekspor',                        'Beban Pokok Penjualan'],
        ['510-15', 'Biaya Operasional Impor',                         'Beban Pokok Penjualan'],
        ['510-16', 'Biaya Online Dokumen',                            'Beban Pokok Penjualan'],
        ['511-00', 'Biaya Transportasi (Biaya Langsung)',             'Beban Pokok Penjualan'],
        ['511-11', 'Biaya Pengiriman & Pengangkutan',                 'Beban Pokok Penjualan'],
        ['511-12', 'Bensin, Tol dan Parkir - Lapangan',              'Beban Pokok Penjualan'],
        ['520-00', 'Biaya Tidak Langsung',                            'Beban Pokok Penjualan'],
        ['520-11', 'Biaya Gaji - Lapangan',                           'Beban Pokok Penjualan'],
        ['520-12', 'Biaya Lembur - Lapangan',                         'Beban Pokok Penjualan'],
        ['520-13', 'Biaya Tunjangan Transport',                       'Beban Pokok Penjualan'],
        ['520-14', 'Biaya Tunjangan Pulsa',                           'Beban Pokok Penjualan'],
        ['520-15', 'Biaya THR & Bonus - Lapangan',                    'Beban Pokok Penjualan'],
        ['520-16', 'Biaya Tunjangan BPJS - Lapangan',                 'Beban Pokok Penjualan'],
        ['530-00', 'Biaya Repair & Maint. (Lapangan)',                'Beban Pokok Penjualan'],
        ['530-10', 'Biaya Keperluan Kendaraan',                       'Beban Pokok Penjualan'],
        ['610-10', 'Biaya Karyawan & Tunjangan',                      'Beban'],
        ['610-11', 'Biaya Gaji - Kantor',                             'Beban'],
        ['610-12', 'Biaya Lembur - Kantor',                           'Beban'],
        ['610-13', 'Biaya Tunjangan Pulsa (Kantor)',                  'Beban'],
        ['610-14', 'Biaya THR & Bonus - Kantor',                      'Beban'],
        ['610-15', 'Biaya Tunjangan BPJS - Kantor',                   'Beban'],
        ['610-17', 'Biaya Pesangon',                                  'Beban'],
        ['610-18', 'Biaya Pendidikan & Latihan',                      'Beban'],
        ['611-10', 'Biaya Perkantoran',                               'Beban'],
        ['611-11', 'Beban Perlengkapan Kantor',                       'Beban'],
        ['611-12', 'Biaya Alat Tulis Kantor & Printing',              'Beban'],
        ['611-13', 'Biaya Kep. RT & Kantor',                          'Beban'],
        ['611-14', 'Biaya Makanan & Minuman',                         'Beban'],
        ['611-15', 'Biaya Pengobatan',                                'Beban'],
        ['611-16', 'Biaya Materai',                                   'Beban'],
        ['611-17', 'Beban Perlengkapan Kerja',                        'Beban'],
        ['611-18', 'Biaya Keamanan dan Kebersihan',                   'Beban'],
        ['611-19', 'Biaya Pembebanan Agunan Leasing',                 'Beban'],
        ['611-20', 'Biaya Buka Rek. Bank Leasing',                   'Beban'],
        ['612-10', 'Biaya Komunikasi',                                'Beban'],
        ['612-11', 'Biaya Telephone',                                 'Beban'],
        ['612-12', 'Iuran & Langganan',                               'Beban'],
        ['613-10', 'Biaya Transportasi (Kantor)',                     'Beban'],
        ['613-11', 'Transportasi',                                    'Beban'],
        ['613-12', 'Biaya Bensin, Tol dan Parkir - Kantor',           'Beban'],
        ['613-14', 'Biaya Perjalanan Dinas',                          'Beban'],
        ['614-00', 'Biaya BPJS',                                      'Beban'],
        ['614-10', 'Biaya BPJS-Ketenagakerjaan',                      'Beban'],
        ['624-10', 'Biaya Utility',                                   'Beban'],
        ['624-11', 'Biaya Air',                                       'Beban'],
        ['624-12', 'Biaya Listrik',                                   'Beban'],
        ['625-10', 'Biaya Pajak & Izin',                              'Beban'],
        ['625-11', 'Biaya Perizinan',                                 'Beban'],
        ['625-12', 'Biaya Legal & Profesional',                       'Beban'],
        ['625-13', 'Biaya PBB',                                       'Beban'],
        ['626-10', 'Biaya Asuransi',                                  'Beban'],
        ['626-11', 'Biaya Asuransi (Umum)',                           'Beban'],
        ['626-12', 'Biaya Asuransi Leasing',                          'Beban'],
        ['627-10', 'Biaya Jamuan & Repr.',                            'Beban'],
        ['627-11', 'Biaya Entertain & Repr',                          'Beban'],
        ['627-12', 'Biaya Sumbangan',                                 'Beban'],
        ['628-10', 'Biaya Sewa',                                      'Beban'],
        ['628-11', 'Biaya Sewa - Bangunan',                           'Beban'],
        ['628-12', 'Biaya Sewa - Kendaraan',                          'Beban'],
        ['628-13', 'Biaya Sewa - Lain - lain',                        'Beban'],
        ['629-10', 'Biaya Repair & Maintenance',                      'Beban'],
        ['629-11', 'Perbaikan & Pemeliharaan',                        'Beban'],
        ['629-12', 'Pemeliharaan Kendaraan',                          'Beban'],
        ['631-10', 'Biaya Iklan & Promosi',                           'Beban'],
        ['631-11', 'Biaya Iklan & Promosi (Detail)',                  'Beban'],
        ['640-90', 'Biaya Pemasaran Lainnya',                         'Beban'],
        ['640-91', 'Beban Operasional Lainnya',                       'Beban'],
        ['700-00', 'Beban Penyusutan & Amortisasi',                   'Beban'],
        ['700-11', 'Biaya Penyusutan - Bangunan',                     'Beban'],
        ['700-12', 'Biaya Penyusutan - Perbaikan Bangunan',           'Beban'],
        ['700-13', 'Biaya Penyusutan - Peralatan Kantor',             'Beban'],
        ['700-14', 'Biaya Penyusutan - Peralatan Kantor (2)',         'Beban'],
        ['700-15', 'Biaya Penyusutan - Kendaraan',                    'Beban'],
        ['700-16', 'Biaya Penyusutan - Kendaraan Leasing',            'Beban'],
        ['720-10', 'Laba/Rugi Terealisasi IDR',                       'Beban Lainnya'],
        ['720-20', 'Laba/Rugi Belum Terealisasi IDR',                 'Beban Lainnya'],
        ['8-80002', '(Laba)/Rugi Pelepasan Aset Tetap',               'Beban Lainnya'],
        ['810-00', 'Pendapatan Lain-Lain',                            'Pendapatan Lainnya'],
        ['810-10', 'Pendapatan Bunga - Bank',                         'Pendapatan Lainnya'],
        ['810-11', 'Pendapatan Bunga - Deposito',                     'Pendapatan Lainnya'],
        ['810-12', 'Pendapatan Komisi - Barang Konsinyasi',           'Pendapatan Lainnya'],
        ['810-20', 'Pendapatan Lain - lain',                          'Pendapatan Lainnya'],
        ['910-00', 'Biaya Lain-Lain',                                 'Beban Lainnya'],
        ['910-11', 'Biaya Administrasi Bank',                         'Beban Lainnya'],
        ['910-12', 'Biaya Pajak Jasa Giro',                           'Beban Lainnya'],
        ['920-11', 'Biaya Bunga Bank',                                'Beban Lainnya'],
        ['920-12', 'Biaya Bunga Leasing',                             'Beban Lainnya'],
        ['920-13', 'Biaya Denda Keterlambatan',                       'Beban Lainnya'],
        ['920-14', 'Biaya Provisi Leasing',                           'Beban Lainnya'],
        ['920-15', 'Biaya Survey Leasing',                            'Beban Lainnya'],
        ['920-16', 'Biaya Administrasi Leasing',                      'Beban Lainnya'],
        ['930-10', 'Biaya Lain-Lain (Misc)',                          'Beban Lainnya'],
        ['980-00', 'Pajak Penghasilan',                               'Beban Lainnya'],
        ['980-11', 'Biaya PPh 21',                                    'Beban Lainnya'],
        ['980-12', 'Biaya PPh 23 Final',                              'Beban Lainnya'],
        ['980-13', 'Biaya PPh 25',                                    'Beban Lainnya'],
        ['980-14', 'Biaya PPh 29',                                    'Beban Lainnya'],
    ];

    public function run(): void
    {
        $imported = 0;
        $skipped  = 0;

        foreach ($this->accounts as [$code, $name, $accurateType]) {
            $m2bType = $this->typeMap[$accurateType] ?? 'beban_operasional';

            // updateOrCreate by code — jika sudah ada, tidak mengubah apapun
            $exists = Account::where('code', $code)->exists();
            if ($exists) {
                $skipped++;
                continue;
            }

            Account::create([
                'code'            => $code,
                'name'            => $name,
                'type'            => $m2bType,
                'opening_balance' => 0,
                'current_balance' => 0,
            ]);
            $imported++;
        }

        $this->command->info("OldDataCoaSeeder: {$imported} imported, {$skipped} skipped (already exist).");
    }
}
